/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kitsu;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author MNA
 */
public class SignupFrame extends javax.swing.JFrame {

    /** Creates new form SignupFrame */
    public SignupFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LINE = new javax.swing.JLabel();
        KITSU = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        KITSU1 = new javax.swing.JLabel();
        KITSU2 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        KITSU3 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        KITSU4 = new javax.swing.JLabel();
        SigUpnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitsu/image 3 (1).png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LINE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitsu/Line 2.png"))); // NOI18N
        LINE.setText("jLabel2");
        jPanel3.add(LINE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, 29));

        KITSU.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        KITSU.setForeground(new java.awt.Color(255, 255, 255));
        KITSU.setText("Cofirm Password");
        jPanel3.add(KITSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 120, -1));

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        jPanel3.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 80, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("EMAIL");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 190, 30));

        KITSU1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        KITSU1.setForeground(new java.awt.Color(255, 255, 255));
        KITSU1.setText("KITSU");
        jPanel3.add(KITSU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        KITSU2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        KITSU2.setForeground(new java.awt.Color(255, 255, 255));
        KITSU2.setText("EMAIL");
        jPanel3.add(KITSU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, 20));

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField2.setText("password");
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 190, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setText("User Name");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 190, 30));

        KITSU3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        KITSU3.setForeground(new java.awt.Color(255, 255, 255));
        KITSU3.setText("User Name");
        jPanel3.add(KITSU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, -1));

        jPasswordField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField3.setText("password");
        jPasswordField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField3MouseClicked(evt);
            }
        });
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 190, 30));

        KITSU4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        KITSU4.setForeground(new java.awt.Color(255, 255, 255));
        KITSU4.setText("Password");
        jPanel3.add(KITSU4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, -1));

        SigUpnButton.setBackground(new java.awt.Color(204, 204, 204));
        SigUpnButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SigUpnButton.setText("Sign Up");
        SigUpnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SigUpnButtonMouseClicked(evt);
            }
        });
        SigUpnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigUpnButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SigUpnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 80, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 340, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        new DashboadFrame().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backButtonMouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        // TODO add your handling code here:
        jPasswordField2.setText("");
    }//GEN-LAST:event_jPasswordField2MouseClicked

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        jTextField2.setText("");

    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jPasswordField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField3MouseClicked
        // TODO add your handling code here:
        jPasswordField3.setText("");
    }//GEN-LAST:event_jPasswordField3MouseClicked

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void SigUpnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigUpnButtonActionPerformed
        String username, email, confirmPassword;
        String  password;
        username = jTextField2.getText();
        email = jTextField1.getText();
        password = jPasswordField3.getText();
        confirmPassword = jPasswordField2.getText();
        System.out.println(username);
        
        boolean checkCapital = password.matches(".*[a-zA-Z]+.*");
        boolean checkNum = password.matches(".*[0-9].*");
        if (!(email.contains("@gmail.com"))){
             JOptionPane.showMessageDialog(null,"Enter a valid Email Address!");
            
        }
        
        else if ((checkNum == false || checkCapital == false || password.length() < 8)){
            JOptionPane.showMessageDialog(null,"Enter a Password that Atleast Contains\n1. Capital Alphabet\n2. A Number\n3. Be 8 Characters long");
            
        }
        
        else if (!(jPasswordField3.getText().equals(jPasswordField2.getText()))){
            JOptionPane.showMessageDialog(null,"Password Mismatch!");
            
        }
        
        else{
            try{

                java.sql.Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","hr","hr");//Nom	hr@//localhost:1521/xe
                Statement stmt = mycon.createStatement();
                stmt.executeUpdate("insert into Accounts values ('"+email+"','"+username+"','"+password+"')");
                JOptionPane.showMessageDialog(null,"Signed Up Successfully!");
                new SigninFrame().setVisible(true);
                this.dispose();
            }   

            catch(SQLException e){
                System.out.println(e.toString());
            }
        
        
        }
    }//GEN-LAST:event_SigUpnButtonActionPerformed

    private void SigUpnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigUpnButtonMouseClicked
        /*String username, password, email, confirmPassword;
        username = jTextField2.getText();
        email = jTextField1.getText();
        while (!(email.contains("@gmail.com"))){
             JOptionPane.showMessageDialog("");
        }
        
        password = jPasswordField3.getText();
        confirmPassword = jPasswordField2.getText();
        System.out.println(username);
        
        try{
            
            java.sql.Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","hr","hr");//Nom	hr@//localhost:1521/xe
            Statement stmt = mycon.createStatement();
            ResultSet result = stmt.executeQuery("Select * from themees");
            while(result.next()){
                System.out.println(result.getString(1));
            }
            
        }   
            
        catch(SQLException e){
            System.out.println(e.toString());
        }*/
    }//GEN-LAST:event_SigUpnButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KITSU;
    private javax.swing.JLabel KITSU1;
    private javax.swing.JLabel KITSU2;
    private javax.swing.JLabel KITSU3;
    private javax.swing.JLabel KITSU4;
    private javax.swing.JLabel LINE;
    private javax.swing.JButton SigUpnButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
